theme = "MyTheme"
copyright = "Nixon Yung"
baseURL = "https://nixonyung.github.io/"
defaultContentLanguage = 'zh'
timeZone = "Asia/Hong_Kong"
[params]
description = "Nixon Yung's Blog"

[languages.zh]
languageCode = 'zh-HK'
languageDirection = 'ltr'
languageName = '粵語'
title = "80% 模仿者"
weight = 1
[languages.en]
languageCode = 'en-HK'
languageDirection = 'ltr'
languageName = 'Chinglish (WIP)'
title = "An 80% Imitator"
weight = 2

[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# style = 'catppuccin-frappe'
# style = 'catppuccin-macchiato'
# style = 'catppuccin-mocha'
# style = "github-dark"
# style = 'onedark'
style = 'vulcan'

[module]
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/mdi'
